name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        # You may pin to the exact commit or the version.
        # uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba
        uses: denoland/setup-deno@v1.1.4
      - name: Install
        run: npm install
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}